import FeedItem from "@/components/feedItem/FeedItem";
import getFeed from "@/utils/getFeed";
import { Navbar, NavbarBrand, NavbarContent } from "@nextui-org/react";
import Head from "next/head";
import useSWR from "swr";

export default function Home() {
  const { data, error, isLoading } = useSWR("getFeed", getFeed);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar className="h-15">
          <NavbarBrand>
            <h1 className="text-xl">redou</h1>
          </NavbarBrand>
      </Navbar>
      <main>
        {data?.map(
          (
            { title, author, date, tags, commentsQuantity, text, topic, views },
            i
          ) => (
            <FeedItem
              key={i}
              title={title}
              author={author}
              date={date}
              tags={tags}
              commentsQuantity={commentsQuantity}
              text={text}
              topic={topic}
              views={views}
            />
          )
        )}
      </main>
    </>
  );
}
